FROM ruby:3.3.6

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install curl wget less vim ssh git default-jdk

COPY add-github-to-known-hosts.sh /add-github-to-known-hosts.sh
RUN chmod +x /add-github-to-known-hosts.sh
RUN /add-github-to-known-hosts.sh

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
